title: "Autopodcast de Marcelo"
description: "Podcast generado automáticamente con IA"
url: "https://cocheloice.github.io/autopodcast"
plugins:
  - jekyll-feed
  - jekyll-podcast

feed:
  path: feed.xml

podcast:
  title: "Autopodcast de Marcelo"
  description: "Podcast generado automáticamente con IA"
  url: "https://cocheloice.github.io/autopodcast"
  feed_url: "https://cocheloice.github.io/autopodcast/feed.xml"
  cover_image: "/cover.jpg"
  author: "Marcelo González"
  categories:
    - "Society & Culture"
