plugins:
  - jekyll-feed
  - jekyll-podcast

feed:
  path: feed.xml

podcast:
  title:       "Autopodcast de Marcelo"
  subtitle:    "Podcast generado automáticamente con IA"
  link:        "https://cocheloice.github.io/autopodcast"
  feed_url:    "https://cocheloice.github.io/autopodcast/feed.xml"
  cover:       "/cover.jpg"
  author:      "Marcelo González"
  categories:
    - "Society & Culture"
